### ISSUE TITLE
Typos and minor wording fixes

### ISSUE THREAD

**Issue by roliverio** [rotdrop/nextcloud-app-files-archive#11]
Hi!

Some typos and grammar/wording fixes, to improve translations:

- Remove hyphens for all ocurrences of: 
    - "end-point", should be: "**endpoint**"
    - "file-name", should be: "**filename**"
    -  "mount-point", should be: "**mount point**"
    -  "base-name", should be: "**basename**"
    -  "pass-phrase", should be: "**passphrase**"
    -  "web-app", should be: "**webapp or simply _app_**"
    -  "archive-extraction", should be: "**archive extraction**"
    -  "archive-file", should be: "**archive file**"
    -  "default-name", should be: "**default name**"
    -  "parent-folder", should be: "**parent folder**"
    - "base-url", should be: "**base url/URL**"
    - "request-URI", should be: "**request URI**" (capitalization of "request" where it applies, of course)
- _"Directory "%s" should be a mount point, but it is not."_ @ lib/Controller/MountController.php, **Line 293**, a suggestion could be: "**Directory "%s" is not a mount point**" (simpler, yet to the point)
- "_Thge personal setting "%1$s" is read-only_" @ lib/Controller/SettingsController.php, **Line 253**, Should be: "**The personal setting "%1$s" is read-only**"
- "_Unrecoverable unknown internal error, no further information available, sorry._" @ src/toolkit/util/ajax.js, **Line 315**, a suggestion could be: "**Unrecoverable unknown internal error, no details available**".
- The message thrown by exception @ lib/Service/AssetService.php in function "getAsset()", **line 87**, would not be easy to translate as it has a hyphen after "resource", i'm not sure how to better word it but is that hyphen in "_%s-resource_" neccesary?

Thanks!

**Comment by rotdrop** [comment]
Just for the reference: I am now pushing v1.06 in order to have a working release in the app-store (v1.0.5 was broken), but it does not contain your translation fixes. This will come with the next release. Thx.

**Comment by rotdrop** [comment]
Should be fixed by commit df5bc304d6b6f623f422112f80abf1f880807cf8.
