### ISSUE TITLE
App icon invisible when using dark theme

### ISSUE THREAD

**Issue by ae5960e8-a6fc-491f-b252-898ecf59af95** [rotdrop/nextcloud-app-files-archive#20]
The app icon present in the menu where the app is triggered does not respect the theme setting of the user, making it invisible. I suggest changing this to the icon which is in the screenshot beside the option "Move or copy" as they are mostly identical.

![image](https://user-images.githubusercontent.com/76442625/212602599-b7f9a8bc-e377-4699-847e-91faf8e354af.png)

**Comment by rotdrop** [comment]
> The app icon present in the menu where the app is triggered does not respect the theme setting of the user, making it invisible. I suggest changing this to the icon which is in the screenshot beside the option "Move or copy" as they are mostly identical.

This is a matter of applying a suitable color transformation to the icon. There are recommendations for this but I forget where. An example is in here

https://github.com/rotdrop/nextcloud-app-files-archive/blob/b1f7b59805c9866187a77f5b40d69503dde6f576/src/PersonalSettings.vue#L185-L190

and

https://github.com/rotdrop/nextcloud-app-files-archive/blob/b1f7b59805c9866187a77f5b40d69503dde6f576/src/PersonalSettings.vue#L204-L208

I fix this eventually, thanks for reporting.

Claus

**Comment by rotdrop** [comment]
This should be fixed in the current release, can you please check, that this is the case?

Thank you!

**Comment by ae5960e8-a6fc-491f-b252-898ecf59af95** [comment]
Fixed in latest version, thanks. :)
