### ISSUE TITLE
Compatibility with Nextcloud version 26

### ISSUE THREAD

**Issue by dimangelid** [rotdrop/nextcloud-app-files-archive#27]
Hello,

We have a Nextcloud 25.0.5 installation and we need to update it to latest Nextcloud 26 version.

We are unable to do so, since this application reports that is not compatible with Nextcloud 26.

@rotdrop when do you plan on releasing a version compatible with Nextcloud 26?

**Comment by IgorA100** [comment]
???

**Comment by rotdrop** [comment]
After a well deserved canoe-holiday in Sweden I am now back and ready to resolve this issue:

-  there are now stableXY release branches which also contain the composer things and the "compiled" JS assets
- the current state of the main-branch was NC 27  compatible for some time. I am just tagging the current state as the next stable release.

**Comment by rotdrop** [comment]
Solved by https://github.com/rotdrop/nextcloud-app-files-archive/releases/tag/v1.1.3
