### ISSUE TITLE
Installed on NC 25.0.10 PHP 7.4.26 -> server error

### ISSUE THREAD

**Issue by pajew** [rotdrop/nextcloud-app-files-archive#28]
Your Composer dependencies require a PHP version ">= 8.0.2". You are running 7.4.26.
Not able to open web interface.
Fortunately possible to disable app with:
docker exec nextcloud occ app:disable files_archive

**Comment by rotdrop** [comment]
Late response from my side. The bad news: the next release of this app will only support NC >= 28 and consequently not PHP 7.x. My test setup actually uses PHP >= 8.2. I am indeed not even sure if the early 8.0.x PHP version are still working. Sorry for that.
