### ISSUE TITLE
not work with nextcloud aio 8.0.0

### ISSUE THREAD

**Issue by JustAnotherRandomUsername** [rotdrop/nextcloud-app-files-archive#36]
**EnduserNotificationException Installation problem; the required resource "files-sidebar-hooks" of type "css" is not installed on the server, please contact the system administrator!
/var/www/html/custom_apps/files_archive/lib/Listener/FilesActionListener.php:179: OCA\FilesArchive\Listener\FilesActionListener::handle: Unable to add style asset files-sidebar-hooks** 

PHP
Version: 8.2.16
Memory limit: 1 GB
Max execution time: 86400
Upload max size: 100 GB
OPcache Revalidate Frequency: 60
Extensions: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, hash, iconv, json, mbstring, SPL, session, PDO, pdo_sqlite, bz2, posix, random, readline, Reflection, standard, SimpleXML, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, apcu, bcmath, Phar, exif, ftp, gd, gmp, imagick, imap, intl, ldap, memcached, pcntl, pdo_pgsql, pgsql, redis, smbclient, sodium, sysvsem, zip, libsmbclient, Zend OPcache

Database
Type: pgsql
Version: PostgreSQL 15.6 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20231014) 13.2.1 20231014, 64-bit
Size: 28 MB

Server (ubuntu 22)
Operating System: Linux 5.15.0-101-generic x86_64
CPU: AMD Ryzen 5 3600 6-Core Processor (12 cores)
Memory: 62.71 GB

Version nextcloud

28.0.3

**Comment by Egor3f** [comment]
The same problem

**Comment by rotdrop** [comment]
Thank you for the bug report. I have time to work on this over the Easter days. Probably  not difficult to correct.

**Comment by rotdrop** [comment]
Well, but this is just something in the log files? Actually, I do not think that the log entries (you do not see the error message in the front end, do you?) are related to the front-end problem, i.e. that nothing happens. Silencing the log-message is resp. was easy but unfortunately this is just not the problem.

**Comment by rotdrop** [comment]
Can you please provide more details? Yes: this error message pops up in the logs because it is explicitly logged if this happens (and the .css is gone, and trying to load it is already fixed in commit 5d48505. But on my side the app works and for supported archive files there is an entry in the action menu of the file and a tab in the side-bar to the right.

So the question is: do we talk here about a real problem or about error messages in the log file? Of course, those should not be there, but the primary goal is of course to have a working app.

My setup is with PHP 8.2 and NC 28.0.4.

**Comment by JustAnotherRandomUsername** [comment]
1) login to nextcloud web-interface with your account (account must have admin rights)
2) go to "apps"
3) go to "files" category
4) find "Archive Manager" press "download and enable"
5) return to you personal folder "All files" and upload archive **type** for example 2.5GB size
6) after successful upload select your archive file with "..." submenu and select "i" (open details)

if **type** of your archive is RAR (RAR archive data, v5) = you will see an error
if **type** of your archive is TAR (POSIX tar archive) = works well
if **type** of your archive is TAR.GZ (POSIX tar archive (GNU) = no submenu

thank you !!!!

**Comment by rotdrop** [comment]
> 1. login to nextcloud web-interface with your account (account must have admin rights)
> 
>     2. go to "apps"
> 
>     3. go to "files" category
> 
>     4. find "Archive Manager" press "download and enable"
> 
>     5. return to you personal folder "All files" and upload archive **type** for example 2.5GB size
> 
>     6. after successful upload select your archive file with "..." submenu and select "i" (open details)
> 
> 
> if **type** of your archive is RAR (RAR archive data, v5) = you will see an error if **type** of your archive is TAR (POSIX tar archive) = works well if **type** of your archive is TAR.GZ (POSIX tar archive (GNU) = no submenu
> 
> thank you !!!!

Sorry, but this really has absolutely nothing to do with your first post. Also, why didn't you mention this first-place? I mean: your error reports are very welcome, but you have to explain yourself in a way that I have a least a slight chance to understand what you mean.

I am closing this now, as the issue you have reported at the start is fixed. Please open a new bug report for the RAR issue.

One word towards that: this app only supports  what is supported by the underlying "unified archive" project. If that cannot handle a particular kind of archive, then this is "won't fix". But please move this to an another issue.

I am now closing this issue as resolve by commit 5d485052784d0a7ce6ef6a6cfb346352ebd1bcf0.
