### ISSUE TITLE
Mount while there is already an existing folder with same name

### ISSUE THREAD

**Issue by TtuxX** [rotdrop/nextcloud-app-files-archive#4]
Hi there,

I ran into a strange issue while testing issue N°2, where I mounted an archive "B" inside a folder "A" that contained an existing folder with name "B" (minus the .zip end of course).

As a result, the original folder, which was shared to external users, was visually replaced by the mounted one.

Would it be possible to make NC files interface display the two folders with a same name but with different icons ? Or add a specific text tag in at the beginning of the mounted folder to differenciate it ? Like "[MOUNT] - Original Archive Name Here" 

Thank you very much.

**Comment by rotdrop** [comment]
This should be fixed by [v1.0.3-rc1](https://github.com/rotdrop/nextcloud-app-files-archive/releases/tag/v1.0.3-rc1):

https://github.com/rotdrop/nextcloud-app-files-archive/blob/v1.0.3-rc1/CHANGELOG.md

**Comment by TtuxX** [comment]
Really awesome, it appears to work really well, thanks! :)

I just have one small issue when there are spaces in the file name:

![image](https://user-images.githubusercontent.com/6570830/201163049-f35066fc-a469-40f2-8441-537aa59e0640.png)

**Comment by rotdrop** [comment]
The problems are not the spaces but the dots. In order to strip double extensions like `.tar.gz` I just pathinfo(PATHINFO_FILENAME) two times. Personally I would probably not name my files the way you did, so these case were not on my mind.

**Comment by rotdrop** [comment]
Can you please check if

2d4fabfdf1ba0c8db9432583fb7d01285a80c261

fixes the problem? Thanks!

**Comment by rotdrop** [comment]
I am closing this as resolved. Feel free to reopen if the problem remains in the current version.

**Comment by TtuxX** [comment]
It works great with the new version. Thanks again ! :)

Maybe UI could be improved/softened a bit as it throws a "frightening" error at the end-user when there is a folder/mount name conflict and auto folder renaming has not been enabled by the Administrator:

Bad Request
The mount point "/XXXX" already exists and auto-rename is not enabled.
Feedback email: [System Administrator]
