### ISSUE TITLE
Can't mount large .zip

### ISSUE THREAD

**Issue by hampoelz** [rotdrop/nextcloud-app-files-archive#44]
I'm not sure if this issue is related to #43, so I created a new one. I've a similar problem but with large (several gigabyte) zip files.

When I try to mount the archive, I also get an http 500 error message: `Failed to mount archive file "/Archives/BigArchive.zip: Request failed with status code 500".`
When I open the archive details view, only `unknown` is displayed as information. In addition, the following error message is shown: `Error: OCA\FilesArchive\Toolkit\Exceptions\ArchiveTooLargeException::__construct(): Argument #3 ($actualSize) must be of type int, array given, called in /var/www/html/custom_apps/files_archive/lib/Toolkit/Service/ArchiveService.php on line 291`

Smaller zip archives can be mounted without problems.

**Comment by rotdrop** [comment]
... I really should establish a test-suit. Help wanted ;)

So this means that you have hit the Zip-Bomp limit (which is configurable, defaults to 4GB) and the error handling itself is broken. #43 is something different. From what you write I would assume that the error should not occur if you increase the administrative Zip-Bomp limit (as administrator, and later as ordinary user). Nevertheless this should be fixed, the idea was to inform the user in this case, not to run into PHP errors in the implementation of the error handling.

**Comment by hampoelz** [comment]
Can confirm that everything is working now. Thank you!
